function summary = summarize_wind_state_probability_records(wind_state_probability_table, cfg)
%SUMMARIZE_WIND_STATE_PROBABILITY_RECORDS Summarize diagnostic P_wt(E_k) records.
if nargin < 2
    cfg = struct();
end
calibration_status = string(get_cfg(cfg, 'wind_trip_parameter_calibration_status', 'unknown'));
if isempty(wind_state_probability_table) || height(wind_state_probability_table) == 0
    summary = table(0, 0, 0, NaN, NaN, NaN, 0, NaN, calibration_status, ...
        "empty wind state probability table", ...
        'VariableNames', {'stage_count', 'valid_stage_count', ...
        'missing_probability_stage_count', 'mean_p_wt_Ek', 'min_p_wt_Ek', ...
        'p05_p_wt_Ek', 'num_stages_with_positive_trip_probability', ...
        'max_p_wt_h_overall', 'calibration_status', 'note'});
    return;
end
p = wind_state_probability_table.p_wt_Ek;
status = string(wind_state_probability_table.status);
valid = ~isnan(p);
summary = table(height(wind_state_probability_table), sum(valid), ...
    sum(status == "missing_probability" | isnan(p)), ...
    mean(p, 'omitnan'), min(p, [], 'omitnan'), percentile_local(p, 5), ...
    sum(wind_state_probability_table.num_probability_positive > 0), ...
    max(wind_state_probability_table.max_p_wt_h, [], 'omitnan'), ...
    calibration_status, ...
    "Record-only diagnostic P_wt(E_k); no wind unit state transition was applied.", ...
    'VariableNames', {'stage_count', 'valid_stage_count', ...
    'missing_probability_stage_count', 'mean_p_wt_Ek', 'min_p_wt_Ek', ...
    'p05_p_wt_Ek', 'num_stages_with_positive_trip_probability', ...
    'max_p_wt_h_overall', 'calibration_status', 'note'});
end

function value = percentile_local(x, p)
x = sort(x(~isnan(x)));
if isempty(x)
    value = NaN;
else
    idx = max(1, min(numel(x), ceil(p / 100 * numel(x))));
    value = x(idx);
end
end

function value = get_cfg(cfg, field_name, default_value)
if isfield(cfg, field_name)
    value = cfg.(field_name);
else
    value = default_value;
end
end
