function scenarios = build_scenario_library(cfg, base_load_mw)
%BUILD_SCENARIO_LIBRARY 构建第4章场景扫描候选库。
% 输入：
%   cfg - 全局配置，包含场景扫描待校准参数。
%   base_load_mw - 系统总负荷，MW；用于按渗透率换算风电容量。
% 输出：
%   scenarios - 结构体数组，每个元素是一组可运行场景。
% 物理含义：
%   明确区分3000 MW基准、工程风速扫描、论文表4-6风速点扫描，避免不同
%   场景族复用或混淆。

if nargin < 2 || isempty(base_load_mw) || isnan(base_load_mw)
    base_load_mw = 6254.23; % 待校准：仅作无法读取case39时的兜底参考
end

scenarios = repmat(empty_scenario(), 0, 1);

scenarios(end + 1) = make_scenario('no_renewable_base', ...
    '无新能源接入，使用原始IEEE39 case39。', 'none', [], 0, NaN, false, NaN, ...
    'baseline', '无新能源对照场景。');

scenarios(end + 1) = make_scenario('distributed_wind_3000mw_base', ...
    '节点30至39分散式接入，总风电容量3000 MW的当前基准场景。', ...
    'wind_plus_redispatch', 30:39, 3000, 12, false, 3000 / base_load_mw, ...
    'baseline', '3000MW基准场景，不代表按base_load定义的40%渗透率。');

scenarios(end + 1) = make_scenario('distributed_wind_40pct', ...
    'legacy别名：节点30至39分散式接入，总风电容量3000 MW。', ...
    'wind_plus_redispatch', 30:39, 3000, 12, false, 3000 / base_load_mw, ...
    'legacy', 'legacy alias for distributed_wind_3000mw_base, not used for penetration_scan.');

scenarios(end + 1) = make_scenario('centralized_wind_40pct', ...
    '集中式风电接入，总风电容量3000 MW。', ...
    'wind_plus_redispatch', cfg.scenario_centralized_wind_bus, 3000, 12, false, 3000 / base_load_mw, ...
    'topology_compare', '集中接入节点暂取配置值，待根据论文或用户设置校准。');

scenarios(end + 1) = make_scenario('distributed_wind_40pct_trip_record_only', ...
    '3000 MW分散式基准场景，启用风机电压脱网概率记录但不实际触发脱网。', ...
    'wind_plus_redispatch', 30:39, 3000, 12, true, 3000 / base_load_mw, ...
    'renewable_trip_record', '当前仅记录脱网概率，未实现完整新能源脱网状态转移；不是渗透率扫描点。');

for ratio = cfg.scenario_penetration_ratios
    scenario_id = sprintf('distributed_wind_penetration_%dpct', round(ratio * 100));
    [total_capacity, cap_detail] = compute_wind_capacity_from_penetration(ratio, cfg);
    scenarios(end + 1) = make_scenario(scenario_id, ...
        sprintf('分散式风电渗透率%.0f%%场景。', ratio * 100), ...
        'wind_plus_redispatch', 30:39, total_capacity, 12, false, ratio, ...
        'penetration_scan', ['容量按compute_wind_capacity_from_penetration换算，basis=', cap_detail.basis, '。']);
end

for wind_speed = cfg.scenario_wind_speed_values_mps
    scenario_id = sprintf('wind_speed_%dmps', round(wind_speed));
    scenarios(end + 1) = make_scenario(scenario_id, ...
        sprintf('分散式3000 MW风电、风速%d m/s工程扫描场景。', round(wind_speed)), ...
        'wind_plus_redispatch', 30:39, 3000, wind_speed, false, 3000 / base_load_mw, ...
        'wind_speed_scan', '风速扫描点为工程设置，待校准；不是论文表4-6风速点。');
end

paper_wind_speeds = [11.28, 11.52, 11.76, 12.00];
paper_source_ids = ["wind_speed_11_28mps", "wind_speed_11_52mps", "wind_speed_11_76mps", "wind_speed_12_00mps"];
for k = 1:numel(paper_wind_speeds)
    scenario_id = "paper_" + paper_source_ids(k);
    scenarios(end + 1) = make_scenario(char(scenario_id), ...
        sprintf('论文表4-6风速点 %.2f m/s，3000 MW分散式风电。', paper_wind_speeds(k)), ...
        'wind_plus_redispatch', 30:39, 3000, paper_wind_speeds(k), false, 3000 / base_load_mw, ...
        'paper_table_4_6_wind_speed', '论文表4-6风速点；当前仍使用line-only paper_formula，未实现P_wt/P_ge。');
    scenarios(end).paper_table = 'Table 4-6';
    scenarios(end).source_paper_scenario_id = char(paper_source_ids(k));
end

% Calibration aliases used only by the reverse-calibration pilot. They do
% not introduce new model logic and must not be interpreted as original
% paper scenario definitions.
scenarios(end + 1) = make_scenario('concentrated_bus34', ...
    'Calibration alias: concentrated wind access at reference bus 34, total wind capacity 3000 MW.', ...
    'wind_plus_redispatch', 34, 3000, 12, false, 3000 / base_load_mw, ...
    'calibration_pilot', 'Benchmark calibration alias; not original-paper calibrated.');
scenarios(end + 1) = make_scenario('distributed_30_39', ...
    'Calibration alias: distributed wind access at buses 30-39, total wind capacity 3000 MW.', ...
    'wind_plus_redispatch', 30:39, 3000, 12, false, 3000 / base_load_mw, ...
    'calibration_pilot', 'Benchmark calibration alias; not original-paper calibrated.');
scenarios(end + 1) = make_scenario('wind_speed_11_28', ...
    'Calibration alias: paper wind speed 11.28 m/s.', ...
    'wind_plus_redispatch', 30:39, 3000, 11.28, false, 3000 / base_load_mw, ...
    'calibration_pilot', 'Benchmark calibration alias; not original-paper calibrated.');
scenarios(end + 1) = make_scenario('wind_speed_12_00', ...
    'Calibration alias: paper wind speed 12.00 m/s.', ...
    'wind_plus_redispatch', 30:39, 3000, 12.00, false, 3000 / base_load_mw, ...
    'calibration_pilot', 'Benchmark calibration alias; not original-paper calibrated.');
for ratio_alias = [0.40, 0.60, 0.80]
    alias_id = sprintf('penetration_%dpct', round(ratio_alias * 100));
    [alias_capacity, alias_detail] = compute_wind_capacity_from_penetration(ratio_alias, cfg);
    scenarios(end + 1) = make_scenario(alias_id, ...
        sprintf('Calibration alias: distributed wind penetration %.0f%%.', ratio_alias * 100), ...
        'wind_plus_redispatch', 30:39, alias_capacity, 12, false, ratio_alias, ...
        'calibration_pilot', ['Benchmark calibration alias; capacity basis=', alias_detail.basis, '; not original-paper calibrated.']);
end
scenarios = annotate_penetration_fields(scenarios, cfg, base_load_mw);
end

function s = empty_scenario()
%EMPTY_SCENARIO 返回统一字段的空场景。
s = struct( ...
    'scenario_id', '', ...
    'description', '', ...
    'renewable_dispatch_mode', '', ...
    'wind_buses', [], ...
    'total_wind_capacity_mw', 0, ...
    'wind_capacity_mw', [], ...
    'wind_speed_mps', NaN, ...
    'cut_in_speed_mps', 3, ...
    'rated_speed_mps', 12, ...
    'cut_out_speed_mps', 25, ...
    'slack_bus', 31, ...
    'renewable_trip_enable', false, ...
    'penetration_ratio', NaN, ...
    'paper_wind_penetration', NaN, ...
    'load_based_wind_penetration', NaN, ...
    'wind_penetration_basis', '', ...
    'paper_aligned_wind_capacity_expected_mw', NaN, ...
    'wind_capacity_basis_match_status', '', ...
    'scenario_group', '', ...
    'calibration_note', '', ...
    'paper_table', '', ...
    'source_paper_scenario_id', '');
end

function s = make_scenario(scenario_id, description, mode, wind_buses, total_capacity, wind_speed, trip_enable, penetration_ratio, scenario_group, note)
%MAKE_SCENARIO 创建单个场景结构体。
s = empty_scenario();
s.scenario_id = scenario_id;
s.description = description;
s.renewable_dispatch_mode = mode;
s.wind_buses = wind_buses;
s.total_wind_capacity_mw = total_capacity;
s.wind_capacity_mw = [];
s.wind_speed_mps = wind_speed;
s.renewable_trip_enable = logical(trip_enable);
s.penetration_ratio = penetration_ratio;
s.scenario_group = scenario_group;
s.calibration_note = note;
end

function scenarios = annotate_penetration_fields(scenarios, cfg, base_load_mw)
paper_total_gen = get_cfg_value(cfg, 'paper_total_generation_capacity_mw', 7500);
for k = 1:numel(scenarios)
    total_capacity = scenarios(k).total_wind_capacity_mw;
    if isempty(total_capacity) || isnan(total_capacity)
        total_capacity = 0;
    end
    scenarios(k).paper_wind_penetration = total_capacity / paper_total_gen;
    scenarios(k).load_based_wind_penetration = total_capacity / base_load_mw;
    if isfield(cfg, 'wind_penetration_basis')
        scenarios(k).wind_penetration_basis = cfg.wind_penetration_basis;
    else
        scenarios(k).wind_penetration_basis = 'base_load';
    end
    if (startsWith(scenarios(k).scenario_id, 'penetration_') || strcmp(scenarios(k).scenario_group, 'penetration_scan')) ...
            && ~isnan(scenarios(k).penetration_ratio)
        expected_capacity = scenarios(k).penetration_ratio * paper_total_gen;
    else
        expected_capacity = total_capacity;
    end
    scenarios(k).paper_aligned_wind_capacity_expected_mw = expected_capacity;
    if abs(total_capacity - expected_capacity) <= 1e-6 * max(1, abs(expected_capacity))
        scenarios(k).wind_capacity_basis_match_status = 'matched';
    else
        scenarios(k).wind_capacity_basis_match_status = 'mismatched';
    end
end
end

function value = get_cfg_value(cfg, field_name, fallback)
if isfield(cfg, field_name) && ~isempty(cfg.(field_name)) && ~isnan(cfg.(field_name))
    value = cfg.(field_name);
else
    value = fallback;
end
end
