function scenarios = build_scenario_library(cfg, base_load_mw)
%BUILD_SCENARIO_LIBRARY 构建第4章场景扫描候选库。
% 输入：
%   cfg - 全局配置，包含场景扫描待校准参数。
%   base_load_mw - 系统总负荷，MW；用于按渗透率换算风电容量。
% 输出：
%   scenarios - 结构体数组，每个元素是一组可运行场景。
% 物理含义：
%   该函数只定义工程场景，不直接运行潮流。论文未明确的集中接入节点、渗透率定义和风速扫描点
%   均保留“待校准”说明，避免把工程假设当成论文参数。

if nargin < 2 || isempty(base_load_mw) || isnan(base_load_mw)
    base_load_mw = 6254.23; % 待校准：仅作为无法读取case39时的兜底近似
end

scenarios = repmat(empty_scenario(), 0, 1);

scenarios(end + 1) = make_scenario('no_renewable_base', ...
    '无新能源接入，使用原始IEEE39 case39。', 'none', [], 0, NaN, false, NaN, ...
    'baseline', '无新能源对照场景。');

scenarios(end + 1) = make_scenario('distributed_wind_40pct', ...
    '节点30至39分散式接入，总风电容量3000 MW。', 'wind_plus_redispatch', 30:39, 3000, 12, false, 0.40, ...
    'smoke_and_full', '3000 MW沿用当前默认场景；渗透率定义待校准。');

scenarios(end + 1) = make_scenario('centralized_wind_40pct', ...
    '集中式风电接入，总风电容量3000 MW。', 'wind_plus_redispatch', cfg.scenario_centralized_wind_bus, 3000, 12, false, 0.40, ...
    'smoke_and_full', '集中接入节点暂取39节点，待根据论文或用户设置校准。');

scenarios(end + 1) = make_scenario('distributed_wind_40pct_trip_record_only', ...
    '分散式40%场景，启用风机电压脱网概率记录但不实际触发脱网。', ...
    'wind_plus_redispatch', 30:39, 3000, 12, true, 0.40, ...
    'full_candidate', '当前仅记录脱网概率，未实现完整新能源脱网状态转移。');

for ratio = cfg.scenario_penetration_ratios
    scenario_id = sprintf('distributed_wind_%dpct', round(ratio * 100));
    if any(strcmp({scenarios.scenario_id}, scenario_id))
        continue;
    end
    total_capacity = ratio * base_load_mw;
    scenarios(end + 1) = make_scenario(scenario_id, ...
        sprintf('分散式风电渗透率%.0f%%场景。', ratio * 100), ...
        'wind_plus_redispatch', 30:39, total_capacity, 12, false, ratio, ...
        'full_candidate', '容量按 风电装机容量/系统总负荷 换算，定义待校准。');
end

for wind_speed = cfg.scenario_wind_speed_values_mps
    scenario_id = sprintf('wind_speed_%dmps', round(wind_speed));
    scenarios(end + 1) = make_scenario(scenario_id, ...
        sprintf('分散式40%%风电、风速%d m/s场景。', round(wind_speed)), ...
        'wind_plus_redispatch', 30:39, 3000, wind_speed, false, 0.40, ...
        'full_candidate', '风速扫描点为工程设置，待校准。');
end
end

function s = empty_scenario()
%EMPTY_SCENARIO 返回统一字段的空场景。
s = struct( ...
    'scenario_id', '', ...
    'description', '', ...
    'renewable_dispatch_mode', '', ...
    'wind_buses', [], ...
    'total_wind_capacity_mw', 0, ...
    'wind_capacity_mw', [], ...
    'wind_speed_mps', NaN, ...
    'cut_in_speed_mps', 3, ...
    'rated_speed_mps', 12, ...
    'cut_out_speed_mps', 25, ...
    'slack_bus', 31, ...
    'renewable_trip_enable', false, ...
    'penetration_ratio', NaN, ...
    'scenario_group', '', ...
    'calibration_note', '');
end

function s = make_scenario(scenario_id, description, mode, wind_buses, total_capacity, wind_speed, trip_enable, penetration_ratio, scenario_group, note)
%MAKE_SCENARIO 创建单个场景结构体。
s = empty_scenario();
s.scenario_id = scenario_id;
s.description = description;
s.renewable_dispatch_mode = mode;
s.wind_buses = wind_buses;
s.total_wind_capacity_mw = total_capacity;
s.wind_capacity_mw = [];
s.wind_speed_mps = wind_speed;
s.renewable_trip_enable = logical(trip_enable);
s.penetration_ratio = penetration_ratio;
s.scenario_group = scenario_group;
s.calibration_note = note;
end
