function generator_state_probability_table = flatten_generator_state_probability_records(chain_records)
%FLATTEN_GENERATOR_STATE_PROBABILITY_RECORDS Expand stage-level P_ge(E_k) diagnostics.
rows = {};
for c = 1:numel(chain_records)
    stages = chain_records(c).stage_records;
    for s = 1:numel(stages)
        if isfield(stages(s), 'generator_state_probability_detail') && ...
                ~isempty(stages(s).generator_state_probability_detail)
            d = stages(s).generator_state_probability_detail;
            rows{end + 1, 1} = table(chain_records(c).initial_branch, chain_records(c).trial_id, ...
                stages(s).stage_id, d.num_traditional_generators, d.num_probability_positive, ...
                d.max_p_g_q, d.mean_p_g_q, d.p_ge_Ek, string(d.status), ...
                string(d.mode), string(d.note), ...
                'VariableNames', {'initial_branch', 'trial_id', 'stage_id', ...
                'num_traditional_generators', 'num_probability_positive', ...
                'max_p_g_q', 'mean_p_g_q', 'p_ge_Ek', 'status', 'mode', 'note'}); %#ok<AGROW>
        end
    end
end
if isempty(rows)
    generator_state_probability_table = empty_table();
else
    generator_state_probability_table = vertcat(rows{:});
end
end

function tbl = empty_table()
tbl = table([], [], [], [], [], [], [], [], strings(0, 1), strings(0, 1), strings(0, 1), ...
    'VariableNames', {'initial_branch', 'trial_id', 'stage_id', ...
    'num_traditional_generators', 'num_probability_positive', ...
    'max_p_g_q', 'mean_p_g_q', 'p_ge_Ek', 'status', 'mode', 'note'});
end
