function summary = summarize_generator_state_probability_records(generator_state_probability_table, cfg)
%SUMMARIZE_GENERATOR_STATE_PROBABILITY_RECORDS Summarize diagnostic P_ge(E_k) records.
calibration_status = string(get_cfg(cfg, 'gen_trip_parameter_calibration_status', 'unknown'));
if isempty(generator_state_probability_table) || height(generator_state_probability_table) == 0
    summary = table(0, 0, 0, NaN, NaN, NaN, 0, NaN, calibration_status, ...
        "No generator state probability records.", ...
        'VariableNames', {'stage_count', 'valid_stage_count', ...
        'missing_probability_stage_count', 'mean_p_ge_Ek', 'min_p_ge_Ek', ...
        'p05_p_ge_Ek', 'num_stages_with_positive_trip_probability', ...
        'max_p_g_q_overall', 'calibration_status', 'note'});
    return;
end
p = generator_state_probability_table.p_ge_Ek;
status = string(generator_state_probability_table.status);
valid = ~isnan(p);
p05 = NaN;
if any(valid)
    p05 = prctile(p(valid), 5);
end
summary = table(height(generator_state_probability_table), sum(valid), ...
    sum(status == "missing_probability" | isnan(p)), mean(p, 'omitnan'), ...
    min(p, [], 'omitnan'), p05, ...
    sum(generator_state_probability_table.num_probability_positive > 0), ...
    max(generator_state_probability_table.max_p_g_q, [], 'omitnan'), ...
    calibration_status, ...
    "Record-only diagnostic; no traditional generator was tripped and P_ge is not integrated into formal paper_formula.", ...
    'VariableNames', {'stage_count', 'valid_stage_count', ...
    'missing_probability_stage_count', 'mean_p_ge_Ek', 'min_p_ge_Ek', ...
    'p05_p_ge_Ek', 'num_stages_with_positive_trip_probability', ...
    'max_p_g_q_overall', 'calibration_status', 'note'});
end

function value = get_cfg(cfg, field_name, default_value)
if isfield(cfg, field_name)
    value = cfg.(field_name);
else
    value = default_value;
end
end
