function unified_table = flatten_unified_state_probability_records(chain_records)
%FLATTEN_UNIFIED_STATE_PROBABILITY_RECORDS Extract unified same-stage probability records.
rows = {};
for c = 1:numel(chain_records)
    stages = chain_records(c).stage_records;
    for s = 1:numel(stages)
        if isfield(stages(s), 'unified_state_probability_detail') && ...
                ~isempty(stages(s).unified_state_probability_detail)
            d = stages(s).unified_state_probability_detail;
            rows{end+1,1} = table(d.initial_branch, d.trial_id, d.stage_id, ...
                string(d.line_parameter_set_id), string(d.wind_parameter_set_id), string(d.generator_parameter_set_id), ...
                d.P_line_Ek, d.P_wt_Ek, d.P_ge_Ek, d.P_total_Ek, ...
                string(d.P_line_status), string(d.P_wt_status), string(d.P_ge_status), ...
                string(d.composite_status), string(d.missing_components), string(d.calibration_status), ...
                logical(d.diagnostic_only), string(d.note), ...
                'VariableNames', {'initial_branch', 'trial_id', 'stage_id', ...
                'line_parameter_set_id', 'wind_parameter_set_id', 'generator_parameter_set_id', ...
                'P_line_Ek', 'P_wt_Ek', 'P_ge_Ek', 'P_total_Ek', ...
                'P_line_status', 'P_wt_status', 'P_ge_status', 'composite_status', ...
                'missing_components', 'calibration_status', 'diagnostic_only', 'note'}); %#ok<AGROW>
        end
    end
end
if isempty(rows)
    unified_table = empty_table();
else
    unified_table = vertcat(rows{:});
end
end

function tbl = empty_table()
tbl = table([], [], [], strings(0, 1), strings(0, 1), strings(0, 1), ...
    [], [], [], [], strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), false(0, 1), strings(0, 1), ...
    'VariableNames', {'initial_branch', 'trial_id', 'stage_id', ...
    'line_parameter_set_id', 'wind_parameter_set_id', 'generator_parameter_set_id', ...
    'P_line_Ek', 'P_wt_Ek', 'P_ge_Ek', 'P_total_Ek', ...
    'P_line_status', 'P_wt_status', 'P_ge_status', 'composite_status', ...
    'missing_components', 'calibration_status', 'diagnostic_only', 'note'});
end
