function summary = summarize_unified_state_probability_records(unified_table)
%SUMMARIZE_UNIFIED_STATE_PROBABILITY_RECORDS Summarize unified composite diagnostics.
if isempty(unified_table) || height(unified_table) == 0
    summary = table(0, 0, 0, NaN, NaN, NaN, NaN, NaN, NaN, 0, 0, 0, ...
        "none", "No unified state probability records.", ...
        'VariableNames', {'stage_count', 'valid_P_total_stage_count', ...
        'missing_P_total_stage_count', 'mean_P_line_Ek', 'mean_P_wt_Ek', ...
        'mean_P_ge_Ek', 'mean_P_total_Ek', 'min_P_wt_Ek', 'min_P_ge_Ek', ...
        'num_wind_affected_stages', 'num_generator_affected_stages', ...
        'num_composite_degenerate_to_line', 'calibration_status', 'note'});
    return;
end
valid = ~isnan(unified_table.P_total_Ek);
degenerate = abs(unified_table.P_total_Ek - unified_table.P_line_Ek) < 1e-12 | ...
    (isnan(unified_table.P_total_Ek) & isnan(unified_table.P_line_Ek));
calibration_status = "diagnostic_assumption_not_paper";
if any(contains(unified_table.calibration_status, "missing"))
    calibration_status = "diagnostic_or_missing_not_paper";
end
summary = table(height(unified_table), sum(valid), sum(~valid), ...
    mean(unified_table.P_line_Ek, 'omitnan'), mean(unified_table.P_wt_Ek, 'omitnan'), ...
    mean(unified_table.P_ge_Ek, 'omitnan'), mean(unified_table.P_total_Ek, 'omitnan'), ...
    min(unified_table.P_wt_Ek, [], 'omitnan'), min(unified_table.P_ge_Ek, [], 'omitnan'), ...
    sum(unified_table.P_wt_Ek < 1), sum(unified_table.P_ge_Ek < 1), sum(degenerate), ...
    calibration_status, ...
    "Unified diagnostic only; no formal paper_formula or final_summary output was replaced.", ...
    'VariableNames', {'stage_count', 'valid_P_total_stage_count', ...
    'missing_P_total_stage_count', 'mean_P_line_Ek', 'mean_P_wt_Ek', ...
    'mean_P_ge_Ek', 'mean_P_total_Ek', 'min_P_wt_Ek', 'min_P_ge_Ek', ...
    'num_wind_affected_stages', 'num_generator_affected_stages', ...
    'num_composite_degenerate_to_line', 'calibration_status', 'note'});
end
