function main_record_wind_speed_scenario_manual_confirmation()
%MAIN_RECORD_WIND_SPEED_SCENARIO_MANUAL_CONFIRMATION Record user-confirmed paper facts.
project_root = fileparts(fileparts(mfilename('fullpath')));
out_dir = fullfile(project_root, 'results', 'calibration', 'wind_speed_scenario_assumption');
ensure_dir(out_dir);

T = table( ...
    true, ...
    "4.5 新能源发电机组出力波动的风险比较", ...
    "Table 4-6", ...
    "11.28,11.52,11.76,12.00", ...
    "11.28: SLLR 7.5361, SLFOR 6.0213, SNVOR 6.5482, CRI 7.0356; 12.00: SLLR 6.6351, SLFOR 4.7631, SNVOR 4.9822, CRI 5.9301", ...
    "risk_decreases_as_wind_speed_approaches_rated_speed", ...
    "not_stated_in_paper", ...
    "not_stated_in_paper", ...
    "not_stated_in_paper", ...
    "not_stated_in_paper", ...
    "not_stated_in_paper", ...
    "not_stated_in_paper", ...
    "User confirmed Table 4-6 values and trend; dispatch, slack, curtailment, baseflow, line loading, and conventional PG details are not stated in the paper.", ...
    "wind_speed_operating_point_sensitivity_baseflow_only", ...
    'VariableNames', {'confirmed_by_user','paper_section','paper_table','confirmed_wind_speeds','confirmed_risk_values','paper_reported_trend','paper_dispatch_assumption_status','paper_conventional_generator_dispatch_status','paper_slack_policy_status','paper_wind_curtailment_status','paper_baseflow_status','paper_line_loading_status','confirmation_note','next_audit_target'});

writetable(T, fullfile(out_dir, 'wind_speed_scenario_manual_confirmation_record.csv'));
fprintf('Wrote %s\n', fullfile(out_dir, 'wind_speed_scenario_manual_confirmation_record.csv'));
end

function ensure_dir(pathname)
if ~exist(pathname, 'dir')
    mkdir(pathname);
end
end
