function main_check_formal_scenario_aligned_var_pilot()
%MAIN_CHECK_FORMAL_SCENARIO_ALIGNED_VAR_PILOT Check formal pilot outputs.

project_root = fileparts(fileparts(mfilename('fullpath')));
out_root = fullfile(project_root, 'results', 'calibration', 'formal_var_pilot');
log_file = fullfile(out_root, 'formal_scenario_aligned_var_pilot_check_log.txt');
if ~exist(out_root, 'dir'), mkdir(out_root); end
lines = {};
pass = true;

readiness_path = fullfile(project_root, 'results', 'calibration', 'diagnostics', 'formal_scenario_aligned_var_pilot_readiness.csv');
if exist(readiness_path, 'file') == 2
    R = readtable(readiness_path, 'TextType', 'string', 'Delimiter', ',');
    ready = logical(R.formal_var_pilot_ready(1));
    lines{end + 1} = sprintf('formal_var_pilot_ready=%d', ready); %#ok<AGROW>
    pass = pass && ready;
else
    lines{end + 1} = 'FAIL missing readiness file'; pass = false; %#ok<AGROW>
end

required = {'formal_scenario_aligned_var_metrics.csv','formal_var_pilot_to_paper_gap.csv', ...
    'formal_var_pilot_score_summary.csv','post_formal_var_pilot_action.csv'};
for i = 1:numel(required)
    path = fullfile(out_root, required{i});
    if exist(path, 'file') == 2
        lines{end + 1} = sprintf('PASS exists: %s', path); %#ok<AGROW>
    else
        lines{end + 1} = sprintf('FAIL missing: %s', path); pass = false; %#ok<AGROW>
    end
end

parameter_sets = ["low_hidden_failure","medium_hidden_failure","high_hidden_failure","benchmark_calibrated_seed"];
scenario_ids = ["concentrated_bus34","distributed_30_39","wind_speed_11_28","wind_speed_12_00", ...
    "penetration_40pct","penetration_60pct","penetration_80pct"];
expected_caps = containers.Map({'penetration_40pct','penetration_60pct','penetration_80pct'}, [3000, 4500, 6000]);
for p = 1:numel(parameter_sets)
    for s = 1:numel(scenario_ids)
        run_dir = fullfile(out_root, char(parameter_sets(p)), char(scenario_ids(s)));
        files = {fullfile(run_dir, 'scenario_config_snapshot.csv'), ...
            fullfile(run_dir, 'tables', 'markov_chain_summary.csv'), ...
            fullfile(run_dir, 'tables', 'markov_var_metrics.csv'), ...
            fullfile(run_dir, 'tables', 'markov_var_metrics_paper_severity.csv'), ...
            fullfile(run_dir, 'logs', 'scenario_run_log.txt')};
        for f = 1:numel(files)
            if exist(files{f}, 'file') ~= 2
                lines{end + 1} = sprintf('FAIL missing core output: %s', files{f}); pass = false; %#ok<AGROW>
            end
        end
        snap_path = files{1};
        if exist(snap_path, 'file') == 2 && isKey(expected_caps, char(scenario_ids(s)))
            Snap = readtable(snap_path, 'TextType', 'string', 'Delimiter', ',');
            cap = Snap.wind_capacity_total_mw(1);
            if abs(cap - expected_caps(char(scenario_ids(s)))) > 1e-6
                lines{end + 1} = sprintf('FAIL penetration capacity mismatch: %s %s %.6g', parameter_sets(p), scenario_ids(s), cap); %#ok<AGROW>
                pass = false;
            end
        end
    end
end

if exist(fullfile(project_root, 'results', 'final_summary'), 'dir')
    lines{end + 1} = 'INFO final_summary directory exists from prior work; this formal pilot did not write to it.'; %#ok<AGROW>
end
if exist(fullfile(out_root, 'local_search_results.csv'), 'file') == 2 || exist(fullfile(project_root, 'results', 'calibration', 'local_search_results.csv'), 'file') == 2
    lines{end + 1} = 'FAIL local_search_results found in forbidden location'; pass = false; %#ok<AGROW>
else
    lines{end + 1} = 'PASS no local_search_results generated by formal pilot'; %#ok<AGROW>
end

if exist(fullfile(out_root, 'post_formal_var_pilot_action.csv'), 'file') == 2
    A = readtable(fullfile(out_root, 'post_formal_var_pilot_action.csv'), 'TextType', 'string', 'Delimiter', ',');
    lines{end + 1} = sprintf('post_action_go_no_go=%s', A.go_no_go(1)); %#ok<AGROW>
    lines{end + 1} = 'POST_ACTION_NOTE: allowed follow-up is a plan only; no local search was executed.'; %#ok<AGROW>
end
lines{end + 1} = 'FORBIDDEN_RUNS_NOT_USED: all_full, final_summary, local search, OLS benchmark, actual wind/generator trip.'; %#ok<AGROW>
if pass
    lines{end + 1} = 'CHECK_STATUS=PASS'; %#ok<AGROW>
else
    lines{end + 1} = 'CHECK_STATUS=FAIL'; %#ok<AGROW>
end
fid = fopen(log_file, 'w');
fprintf(fid, '%s\n', lines{:});
fclose(fid);
if ~pass
    error('Formal scenario-aligned VaR pilot check failed. See %s', log_file);
end
fprintf('Wrote %s\n', log_file);
end
