function main_build_severity_formula_manual_confirmation_questions()
% Build the manual question list needed before any severity formula change.

root = fileparts(fileparts(mfilename('fullpath')));
out_dir = fullfile(root, 'results', 'calibration', 'severity_formula');
ensure_dir(out_dir);

rows = {};
rows{end+1,1}=q("Q1","LLR/SLLR","What is the paper definition of LLR or SLLR?", ...
    "LLR drives the load-loss contribution to CRI and may be stage-level or chain-level.", ...
    "lost load MW divided by total load", "lost load ratio already probability-weighted", "final-chain or maximum-chain load-loss severity", ...
    "Keep or adjust current normalization only.", "Risk probability aggregation must move outside severity.", "Change aggregation level before rerun.", ...
    "Please provide the paper screenshot or exact equation for LLR/SLLR.", "");
rows{end+1,1}=q("Q2","LFOR/SLFOR","What is the paper definition of LFOR or SLFOR?", ...
    "The current code uses max overload excess times max(overloaded line count,1), but this is not paper-confirmed.", ...
    "count of overloaded lines", "sum of all overload magnitudes", "maximum overload rate or normalized overload index", ...
    "Replace magnitude formula with count-based formula.", "Use branch-wise summation and likely normalize by branch count.", "Use maximum-overload formula.", ...
    "Please provide the LFOR/SLFOR equation and any normalization basis.", "");
rows{end+1,1}=q("Q3","NVOR/SNVOR","What is the paper definition of NVOR or SNVOR?", ...
    "Voltage severity can change sharply depending on count, max deviation, sum deviation, and upper/lower handling.", ...
    "count of violated buses", "sum of voltage deviations beyond limits", "maximum voltage deviation or normalized index", ...
    "Use count-based voltage severity.", "Use bus-wise deviation summation.", "Keep or adjust current max-deviation logic.", ...
    "Please provide the NVOR/SNVOR equation and voltage limit convention.", "");
rows{end+1,1}=q("Q4","CRI","What is the paper definition of CRI?", ...
    "CRI combines components, so weight and normalization choices determine benchmark direction.", ...
    "CRI = 0.6*SLLR + 0.2*SLFOR + 0.2*SNVOR", "same weights but components normalized first", "different weights or nonlinear aggregation", ...
    "Keep current CRI if components are confirmed.", "Add/confirm component normalization.", "Implement confirmed alternative CRI only in paper-confirmed mode.", ...
    "Please provide CRI equation, weights, and whether the weights are fixed.", "");
rows{end+1,1}=q("Q5","severity_stage_or_chain_level","Are severity metrics computed per stage, final state, whole chain cumulative value, maximum over chain, or VaR sample?", ...
    "Current recompute audit suggests trace semantics may be mixed or chain-level rather than clean stage-level.", ...
    "stage-level severity", "final/terminal chain severity", "whole-chain cumulative or max-over-chain severity", ...
    "Use stage fields directly for probability-weighted stage risk.", "Use terminal stage only.", "Change trace aggregation and VaR sample construction.", ...
    "Please confirm the paper's accident-chain severity aggregation level.", "");
rows{end+1,1}=q("Q6","nonconvergence_handling","How should nonconverged accident stages/chains be handled?", ...
    "The current code lower-bounds SLLR/SLFOR/SNVOR to at least 1 when PF does not converge.", ...
    "assign maximum severity", "exclude invalid chains/stages", "derive severity from last solvable state or load-shed result", ...
    "Current lower-bound logic may be acceptable.", "Invalid-stage filtering changes tail risk.", "Need replay/trace of last valid state.", ...
    "Please confirm the paper's treatment of nonconverged power flow states.", "");
rows{end+1,1}=q("Q7","zero_violation_handling","When there is no line overload or voltage violation, should SLFOR/SNVOR be exactly zero?", ...
    "The current code uses max(count,1), so the magnitude term controls zero; this must be confirmed.", ...
    "zero if no violation", "keep max(count,1) multiplier with zero magnitude", "use a small baseline severity", ...
    "Formula can explicitly force zero.", "Current implementation may be equivalent if magnitude is zero.", "Baseline risk must be introduced and justified.", ...
    "Please confirm zero-violation handling for line and voltage severity.", "");

T = vertcat(rows{:});
writetable(T, fullfile(out_dir, 'severity_formula_manual_confirmation_questions.csv'));
end

function T=q(id,item,question,why,A,B,C,impactA,impactB,impactC,required,note)
T=table(string(id),string(item),string(question),string(why),string(A),string(B),string(C), ...
    string(impactA),string(impactB),string(impactC),string(required),string(note), ...
    'VariableNames',{'question_id','severity_item','question','why_it_matters','possible_answer_A','possible_answer_B','possible_answer_C','impact_if_A','impact_if_B','impact_if_C','required_user_input','note'});
end

function ensure_dir(path)
if exist(path,'dir')~=7, mkdir(path); end
end
