function main_build_severity_formula_next_step_branch_plan()
% Build allowed next-step branches after the user confirms severity formulas.

root = fileparts(fileparts(mfilename('fullpath')));
out_dir = fullfile(root, 'results', 'calibration', 'severity_formula');
ensure_dir(out_dir);

rows = {};
rows{end+1,1}=r("user_confirms_current_code_formulas", ...
    "Current LLR/LFOR/NVOR/CRI formulas can remain as diagnostic/formal implementation after confirmation.", ...
    "increase wind-speed-only trials with confirmed formulas or inspect tail composition", ...
    "local search or parameter tuning before confirming probability inputs", ...
    "none", "wind-speed-only diagnostic rerun with explicit confirmed-formula label", "");
rows{end+1,1}=r("user_confirms_different_LFOR_formula", ...
    "Line overload severity differs from current code.", ...
    "implement confirmed LFOR formula then run formula smoke and wind-speed-only diagnostic rerun", ...
    "change unrelated probability parameters or tune to hide mismatch", ...
    "update calc_basic_risk_metrics.m only under paper-confirmed mode", ...
    "formula smoke plus wind-speed-only diagnostic rerun", "");
rows{end+1,1}=r("user_confirms_different_NVOR_formula", ...
    "Voltage-overrun severity differs from current code.", ...
    "implement confirmed NVOR formula then run formula smoke and wind-speed-only diagnostic rerun", ...
    "change Markov sampling, line probability, or benchmark files", ...
    "update calc_basic_risk_metrics.m only under paper-confirmed mode", ...
    "formula smoke plus voltage severity trace audit", "");
rows{end+1,1}=r("user_confirms_different_LLR_formula", ...
    "Load-loss severity normalization or aggregation differs from current code.", ...
    "implement confirmed LLR formula then rerun diagnostic", ...
    "treat current total_load_shed/base_load as paper-confirmed", ...
    "update LLR branch in calc_basic_risk_metrics.m only after confirmation", ...
    "LLR recompute audit and targeted scenario rerun", "");
rows{end+1,1}=r("user_confirms_stage_level_or_chain_level_difference", ...
    "Severity trace aggregation level is different from current diagnostic interpretation.", ...
    "adjust severity trace aggregation level then rerun diagnostic", ...
    "modify component formulas before fixing aggregation semantics", ...
    "update trace aggregation/export logic, not probability model", ...
    "stage-vs-chain trace comparison smoke", "");
rows{end+1,1}=r("user_says_formula_not_clear", ...
    "Original formula remains unavailable.", ...
    "keep current code as diagnostic assumption; do not tune to hide uncertainty; increase wind-speed-only trials or document uncertainty", ...
    "claim strict reproduction or formal paper formula", ...
    "none", "document uncertainty and optionally run non-formal sensitivity", "");

writetable(vertcat(rows{:}), fullfile(out_dir, 'severity_formula_next_step_branch_plan.csv'));
end

function T=r(outcome, interp, allowed, forbidden, change, diagnostic, note)
T=table(string(outcome),string(interp),string(allowed),string(forbidden),string(change),string(diagnostic),string(note), ...
    'VariableNames',{'confirmation_outcome','interpretation','allowed_next_step','forbidden_next_step','required_code_change','required_diagnostic','note'});
end

function ensure_dir(path)
if exist(path,'dir')~=7, mkdir(path); end
end
