function main_build_PL_formula_manual_confirmation_evidence_pack()
root = fileparts(fileparts(mfilename('fullpath')));
out_dir = fullfile(root, 'results', 'calibration', 'event_probability_formula');
ensure_dir(out_dir);
rows = {};
rows{end+1,1} = evidence("E001", "src/outage/compute_paper_line_outage_probability.m", "lines around P1/P2/P_L implementation", ...
    "P1/P2/P3/P_L", "P1 = P_flow*(1-P_in_r)*(1-P_in_c); P2 = P_mis_c + P_mis_r*(1-P_in_c); P_L = clip(P1+P2+P3)", ...
    "current_code_implementation uses clipped simple sum", true, false, true, false, "code_implementation", ...
    "Need original paper screenshot confirming whether this is formula text or implementation assumption.", ...
    "Code evidence is not original paper evidence.");
rows{end+1,1} = evidence("E002", "results/calibration/event_probability_formula/PL_event_probability_formula_implementation_audit.csv", "formula audit rows", ...
    "P_L", "Available extracted inputs did not confirm independent union/inclusion-exclusion.", ...
    "manual confirmation required", false, false, false, true, "extracted_note", ...
    "Need original paper formula context around P_L.", "Do not change formula based on proxy materiality alone.");
rows{end+1,1} = evidence("E003", "results/calibration/event_probability_formula/PL_sum_vs_union_difference_audit.csv", "materiality diagnostic", ...
    "P_L simple sum vs union", "Simple sum and independent union differ materially in existing diagnostic traces.", ...
    "diagnostic materiality only", false, false, false, true, "diagnostic_assumption", ...
    "Need paper confirmation before deciding formula.", "Material difference shows the question matters, not which formula is correct.");
rows{end+1,1} = evidence("E004", "src/cascade/compute_stage_transition_probability_from_candidates.m", "stage probability aggregation", ...
    "candidate probability", "Full Bernoulli stage event multiplies selected p and unselected (1-p).", ...
    "candidate probability is treated as line outage probability entering Markov event aggregation", true, false, false, false, "code_implementation", ...
    "Need paper confirmation for candidate outage probability to Markov transition mapping.", ...
    "Stage Bernoulli aggregation is code behavior, not necessarily paper-confirmed.");
rows{end+1,1} = evidence("E005", "paper_inputs/filled and paper_inputs/validated", "searched formula records", ...
    "P_L formula", "missing_original_formula", "no original paper screenshot/formula text in current repository proving union or mutual exclusivity", ...
    false, false, false, true, "missing", "Need user-provided formula screenshot or exact text.", ...
    "Repository inputs are insufficient for a safe formula change.");
writetable(vertcat(rows{:}), fullfile(out_dir, 'PL_formula_manual_confirmation_evidence.csv'));
end

function T = evidence(id, file, section, sym, text, interp, simple, unionp, clipped, other, strength, missing, note)
T = table(string(id), string(file), string(section), string(sym), string(text), string(interp), logical(simple), logical(unionp), ...
    logical(clipped), logical(other), string(strength), string(missing), string(note), ...
    'VariableNames', {'evidence_id','source_file','source_section_or_line','formula_symbol','formula_text','formula_interpretation', ...
    'supports_simple_sum','supports_independent_union','supports_clipped_sum','supports_other','evidence_strength','missing_information','note'});
end

function ensure_dir(path)
if exist(path,'dir')~=7, mkdir(path); end
end
