function main_reconcile_full_event_zero_and_selection_audit()
%MAIN_RECONCILE_FULL_EVENT_ZERO_AND_SELECTION_AUDIT Reconcile zero-probability diagnosis with terminal-aware selection audit.
project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root, 'config'));
addpath(genpath(fullfile(project_root, 'src')));

root_dir = fullfile(project_root, 'results', 'calibration', 'transition_probability');
raw_summary = readtable(fullfile(root_dir, 'candidate_selection_consistency_summary.csv'), 'TextType', 'string');
ta_summary = readtable(fullfile(root_dir, 'candidate_selection_consistency_terminal_aware_summary.csv'), 'TextType', 'string');
stage_tbl = readtable(fullfile(root_dir, 'full_event_trace_smoke', 'stage_transition_probability_details.csv'), 'TextType', 'string');
chain_tbl = readtable(fullfile(root_dir, 'full_event_trace_smoke', 'markov_chain_summary.csv'), 'TextType', 'string');
zero_diag = readtable(fullfile(root_dir, 'full_event_zero_probability_diagnosis.csv'), 'TextType', 'string'); %#ok<NASGU>

items = {};
items{end+1,1} = make_row("raw inconsistent_count", raw_summary.inconsistent_count(1), ...
    ta_summary.inconsistent_nonterminal_count(1), ...
    "Raw inconsistencies include terminal residual candidates.", false, ...
    "Use terminal-aware audit for formal rerun gate.", "Raw audit remains useful but is not terminal-aware.");
items{end+1,1} = make_row("terminal-aware inconsistent_nonterminal_count", raw_summary.inconsistent_count(1), ...
    ta_summary.inconsistent_nonterminal_count(1), ...
    "Nonterminal sampling consistency is the blocking quantity.", ta_summary.inconsistent_nonterminal_count(1) > 0, ...
    "Fix nonterminal selection trace if nonzero.", "");
items{end+1,1} = make_row("terminal stage excluded count", NaN, ta_summary.terminal_exclusion_count(1), ...
    "Terminal residual candidates are excluded from sampling consistency.", false, ...
    "No fix needed if only terminal residual candidates remain.", "");

all_chain_full = all(string(chain_tbl.chain_probability_status) == "full_event_available");
items{end+1,1} = make_row("chain_probability_status full_event_available", NaN, double(all_chain_full), ...
    "All chains must have full_event_available before formal rerun.", ~all_chain_full, ...
    "Fix chain probability status if false.", "");
inconsistent_stage_count = sum(string(stage_tbl.probability_status) == "inconsistent_candidate_selection" | ...
    string(stage_tbl.probability_status) == "inconsistent_random_selection");
items{end+1,1} = make_row("stage_probability_status inconsistent count", NaN, inconsistent_stage_count, ...
    "Inconsistent full-event stages block formal rerun.", inconsistent_stage_count > 0, ...
    "Fix stage selection consistency.", "");
ambiguous_count = sum(string(stage_tbl.probability_status) == "ambiguous_terminal_stage");
items{end+1,1} = make_row("stage_probability_status ambiguous_terminal_stage count", NaN, ambiguous_count, ...
    "Ambiguous terminal stages block formal rerun.", ambiguous_count > 0, ...
    "Fix terminal stage classification.", "");
nan_chain_count = sum(isnan(chain_tbl.chain_transition_probability));
items{end+1,1} = make_row("full_event chain probability NaN count", NaN, nan_chain_count, ...
    "NaN chain probabilities block formal rerun.", nan_chain_count > 0, ...
    "Do not replace NaN with selected-only.", "");
zero_chain_count = sum(chain_tbl.chain_transition_probability == 0);
items{end+1,1} = make_row("full_event chain probability unreasonable zero count", NaN, zero_chain_count, ...
    "After terminal fix, zero should only remain if diagnosed as true no-new-outage full event or inconsistency.", zero_chain_count > 0, ...
    "Inspect zero diagnosis if nonzero.", "");

out = vertcat(items{:});
writetable(out, fullfile(root_dir, 'full_event_zero_selection_reconciliation.csv'));
fprintf('full-event zero/selection reconciliation written: %s\n', root_dir);
end

function row = make_row(item, raw_value, terminal_value, interpretation, blocking, fix, note)
row = table(string(item), raw_value, terminal_value, string(interpretation), logical(blocking), string(fix), string(note), ...
    'VariableNames', {'diagnosis_item', 'raw_value', 'terminal_aware_value', ...
    'interpretation', 'blocking_for_formal_rerun', 'recommended_fix', 'note'});
end
