function main_record_PL_formula_manual_confirmation()
root = fileparts(fileparts(mfilename('fullpath')));
out_dir = fullfile(root, 'results', 'calibration', 'event_probability_formula');
ensure_dir(out_dir);
T = table(true, "P_L = P1 + P2 + P3", ...
    "P1 = P(L) * (1 - P_in_r) * (1 - P_in_c)", ...
    "P2 = P_mis_c + P_mis_r * (1 - P_in_c)", ...
    "P_mis_r = P_HF_D + P_HF_L - P_HF_D * P_HF_L", ...
    "P3 is other-factor line outage probability such as secondary equipment aging, operation error, extreme weather; treated as constant.", ...
    true, true, "user_manual_confirmation_from_paper_formula_3_6", ...
    "User confirmed paper formula (3-6) uses simple sum; union/inclusion-exclusion is rejected as formula replacement.", ...
    "stage_probability_aggregation_or_severity_response", ...
    'VariableNames', {'confirmed_by_user','confirmed_formula','confirmed_P1_formula','confirmed_P2_formula', ...
    'confirmed_Pmis_r_formula','confirmed_P3_interpretation','union_formula_rejected','inclusion_exclusion_rejected', ...
    'confirmation_source','confirmation_note','next_audit_target'});
writetable(T, fullfile(out_dir, 'PL_formula_manual_confirmation_record.csv'));
end

function ensure_dir(path)
if exist(path,'dir')~=7, mkdir(path); end
end
