function main_audit_wind_trip_probability_input_sources()
%MAIN_AUDIT_WIND_TRIP_PROBABILITY_INPUT_SOURCES Audit P_WT input availability.
project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root, 'config'));
addpath(genpath(fullfile(project_root, 'src')));
out_dir = fullfile(project_root, 'results', 'calibration', 'renewable_trip');
ensure_dir(out_dir);

after_root = fullfile(project_root, 'results', 'calibration', 'full_event_formal_var_pilot_after_curve_fix');
sample_stage_voltage = fullfile(after_root, 'low_hidden_failure', 'wind_speed_11_28', 'tables', 'markov_bus_voltage_details.csv');
sample_wind_trace = fullfile(out_dir, 'wind_trip_record_smoke', 'wind_speed_11_28', 'wind_trip_probability_trace.csv');
formula_file = fullfile(project_root, 'paper_inputs', 'filled', 'wind_trip_probability_formula.csv');

rows = [
    row("wind_bus_voltage_pu", exist(sample_wind_trace, 'file') == 2, sample_wind_trace, "U_pu", true, ...
        "Available after wind_trip_record_smoke; unavailable in old formal pilot if trace is missing.", ...
        "Run record-only wind trip smoke or enable record-only tracing in a future formal pilot.", "No wind state is changed.")
    row("system_frequency_hz", true, "config/base_config.m", "cfg.system_frequency_hz", true, ...
        "Static power flow has no dynamic frequency; nominal 50 Hz is diagnostic only.", ...
        "Use dynamic frequency if a dynamic model becomes available.", "Do not claim nominal frequency is real dynamic frequency.")
    row("pcc_frequency_hz", false, "", "", false, ...
        "No PCC frequency record found in current static Markov outputs.", ...
        "Add PCC frequency source only if dynamic simulation or paper mapping is provided.", "")
    row("generator_frequency_hz", false, "", "", false, ...
        "No generator-specific dynamic frequency record found.", ...
        "Do not fabricate generator/wind unit frequency.", "")
    row("stage_power_flow_bus_voltage", exist(sample_stage_voltage, 'file') == 2, sample_stage_voltage, "bus voltage columns", true, ...
        "Formal pilot stores bus voltage diagnostics, but not wind P_WT trace by default.", ...
        "Use wind bus voltage from pf_result in record-only tracing.", "")
    row("renewable_trip_event_record", exist(sample_wind_trace, 'file') == 2, sample_wind_trace, "P_wt", false, ...
        "Current trace is probability record only, not actual trip event transition.", ...
        "Keep actual wind trip state transition disabled.", "")
    row("wind_speed_input", true, "scenario library / scenario_config_snapshot.csv", "wind_speed_mps", true, ...
        "Wind speed is available for wind_speed_11_28 and wind_speed_12_00.", ...
        "Keep paper_2_12_20 curve for benchmark-aligned diagnostics.", "")
    row("wind_power_output", true, "scenario_config_snapshot.csv", "actual_wind_pg_total_mw_in_case", true, ...
        "Wind active power is available in scenario snapshots.", ...
        "Do not use this as a substitute for P_WT voltage/frequency probability.", "")
    row("wind_trip_probability_formula", exist(formula_file, 'file') == 2, formula_file, "formula_text", true, ...
        "Paper thresholds are fixed; interval function remains diagnostic unless confirmed.", ...
        "Keep source_status visible in all outputs.", "")
    ];
writetable(rows, fullfile(out_dir, 'wind_trip_probability_input_source_audit.csv'));
end

function t = row(source_item, available, source_file, source_field, usable, limitation, recommended_fix, note)
t = table(string(source_item), logical(available), string(source_file), string(source_field), logical(usable), ...
    string(limitation), string(recommended_fix), string(note), ...
    'VariableNames', {'source_item', 'available', 'source_file', 'source_field', ...
    'usable_for_paper_wt_probability', 'limitation', 'recommended_fix', 'note'});
end

function ensure_dir(path)
if ~exist(path, 'dir'), mkdir(path); end
end
