function [line_flow_summary_table, bus_voltage_summary_table, stage_probability_summary_table] = ...
    summarize_paper_detail_tables(line_flow_detail_table, bus_voltage_detail_table, stage_probability_table, invalid_stage_detail_table)
%SUMMARIZE_PAPER_DETAIL_TABLES 汇总paper_formula三类明细表。
% 输入：
%   line_flow_detail_table - 仅有效stage的线路有功潮流明细。
%   bus_voltage_detail_table - 仅有效stage的节点电压明细。
%   stage_probability_table - 所有stage的概率与有效性标记。
%   invalid_stage_detail_table - 无效stage诊断表。
% 输出：
%   line_flow_summary_table、bus_voltage_summary_table、stage_probability_summary_table。
% 物理含义：
%   summary只统计severity_valid=1的物理有效行，并显式记录被排除的无效stage数量。

if nargin < 4
    invalid_stage_detail_table = table();
end
invalid_or_excluded_stage_count = height(invalid_stage_detail_table);

line_inf = any(isinf(line_flow_detail_table.line_severity_component));
line_nan = any(isnan(line_flow_detail_table.line_severity_component));
line_flow_summary_table = table( ...
    height(line_flow_detail_table), ...
    height(line_flow_detail_table), ...
    invalid_or_excluded_stage_count, ...
    count_unique_chains(line_flow_detail_table), ...
    count_unique_stages(line_flow_detail_table), ...
    max_or_nan(line_flow_detail_table.P_li_pu), ...
    max_or_nan(line_flow_detail_table.line_overlimit_component), ...
    max_or_nan(line_flow_detail_table.line_severity_component), ...
    sum(line_flow_detail_table.line_overlimit_component > 0), ...
    percentile_value(line_flow_detail_table.P_li_pu, 95), ...
    percentile_value(line_flow_detail_table.line_severity_component, 95), ...
    double(line_inf), double(line_nan), ...
    'VariableNames', {'total_rows', 'valid_row_count', 'invalid_or_excluded_stage_count', ...
    'unique_chain_count', 'unique_stage_count', 'max_P_li_pu', ...
    'max_line_overlimit_component', 'max_line_severity_component', 'num_overlimit_rows', ...
    'p95_P_li_pu', 'p95_line_severity_component', 'has_inf_severity', 'has_nan_severity'});

bus_inf = any(isinf(bus_voltage_detail_table.voltage_severity_component));
bus_nan = any(isnan(bus_voltage_detail_table.voltage_severity_component));
bus_voltage_summary_table = table( ...
    height(bus_voltage_detail_table), ...
    height(bus_voltage_detail_table), ...
    invalid_or_excluded_stage_count, ...
    count_unique_chains(bus_voltage_detail_table), ...
    count_unique_stages(bus_voltage_detail_table), ...
    min_or_nan(bus_voltage_detail_table.voltage_pu), ...
    max_or_nan(bus_voltage_detail_table.voltage_pu), ...
    max_or_nan(bus_voltage_detail_table.voltage_deviation_component), ...
    max_or_nan(bus_voltage_detail_table.voltage_severity_component), ...
    sum(bus_voltage_detail_table.voltage_deviation_component > 0), ...
    percentile_value(bus_voltage_detail_table.voltage_severity_component, 95), ...
    double(bus_inf), double(bus_nan), ...
    'VariableNames', {'total_rows', 'valid_row_count', 'invalid_or_excluded_stage_count', ...
    'unique_chain_count', 'unique_stage_count', 'min_voltage_pu', 'max_voltage_pu', ...
    'max_voltage_deviation_component', 'max_voltage_severity_component', ...
    'num_voltage_violation_rows', 'p95_voltage_severity_component', ...
    'has_inf_severity', 'has_nan_severity'});

stage_probability_summary_table = table( ...
    height(stage_probability_table), ...
    count_unique_chains(stage_probability_table), ...
    max(stage_probability_table.stage_id), ...
    min(stage_probability_table.stage_cumulative_probability), ...
    max(stage_probability_table.stage_cumulative_probability), ...
    sum(stage_probability_table.stage_cumulative_probability == 0), ...
    sum(isnan(stage_probability_table.stage_cumulative_probability)), ...
    max(stage_probability_table.stage_load_shed_frac), ...
    sum(stage_probability_table.severity_valid == 1), ...
    sum(stage_probability_table.severity_valid == 0), ...
    'VariableNames', {'total_rows', 'unique_chain_count', 'max_stage_id', ...
    'min_stage_cumulative_probability', 'max_stage_cumulative_probability', ...
    'num_zero_stage_probability', 'num_nan_stage_probability', 'max_stage_load_shed_frac', ...
    'valid_stage_count', 'invalid_stage_count'});
end

function n = count_unique_chains(tbl)
if isempty(tbl)
    n = 0;
else
    keys = string(tbl.initial_branch) + "_" + string(tbl.trial_id);
    n = numel(unique(keys));
end
end

function n = count_unique_stages(tbl)
if isempty(tbl)
    n = 0;
else
    keys = string(tbl.initial_branch) + "_" + string(tbl.trial_id) + "_" + string(tbl.stage_id);
    n = numel(unique(keys));
end
end

function value = percentile_value(values, pct)
values = sort(values(~isnan(values)));
if isempty(values)
    value = NaN;
    return;
end
idx = max(1, min(numel(values), ceil(pct / 100 * numel(values))));
value = values(idx);
end

function value = max_or_nan(values)
if isempty(values)
    value = NaN;
else
    value = max(values);
end
end

function value = min_or_nan(values)
if isempty(values)
    value = NaN;
else
    value = min(values);
end
end
