function [line_flow_summary_table, bus_voltage_summary_table, stage_probability_summary_table] = ...
    summarize_paper_detail_tables(line_flow_detail_table, bus_voltage_detail_table, stage_probability_table)
%SUMMARIZE_PAPER_DETAIL_TABLES 汇总paper_formula三类明细表。
% 输入：
%   line_flow_detail_table - 每级全线路有功潮流明细。
%   bus_voltage_detail_table - 每级全节点电压明细。
%   stage_probability_table - 每级状态概率明细。
% 输出：
%   line_flow_summary_table - 线路潮流明细统计摘要。
%   bus_voltage_summary_table - 节点电压明细统计摘要。
%   stage_probability_summary_table - 阶段概率明细统计摘要。
% 物理含义：
%   summary用于快速判断full CSV和chunks是否包含真实paper_formula状态数据，而不是空表或表头。

line_flow_summary_table = table( ...
    height(line_flow_detail_table), ...
    count_unique_chains(line_flow_detail_table), ...
    count_unique_stages(line_flow_detail_table), ...
    max(line_flow_detail_table.P_li_pu), ...
    max(line_flow_detail_table.line_overlimit_component), ...
    max(line_flow_detail_table.line_severity_component), ...
    sum(line_flow_detail_table.line_overlimit_component > 0), ...
    percentile_value(line_flow_detail_table.P_li_pu, 95), ...
    percentile_value(line_flow_detail_table.line_severity_component, 95), ...
    'VariableNames', {'total_rows', 'unique_chain_count', 'unique_stage_count', ...
    'max_P_li_pu', 'max_line_overlimit_component', 'max_line_severity_component', ...
    'num_overlimit_rows', 'p95_P_li_pu', 'p95_line_severity_component'});

bus_voltage_summary_table = table( ...
    height(bus_voltage_detail_table), ...
    count_unique_chains(bus_voltage_detail_table), ...
    count_unique_stages(bus_voltage_detail_table), ...
    min(bus_voltage_detail_table.voltage_pu), ...
    max(bus_voltage_detail_table.voltage_pu), ...
    max(bus_voltage_detail_table.voltage_deviation_component), ...
    max(bus_voltage_detail_table.voltage_severity_component), ...
    sum(bus_voltage_detail_table.voltage_deviation_component > 0), ...
    percentile_value(bus_voltage_detail_table.voltage_severity_component, 95), ...
    'VariableNames', {'total_rows', 'unique_chain_count', 'unique_stage_count', ...
    'min_voltage_pu', 'max_voltage_pu', 'max_voltage_deviation_component', ...
    'max_voltage_severity_component', 'num_voltage_violation_rows', ...
    'p95_voltage_severity_component'});

stage_probability_summary_table = table( ...
    height(stage_probability_table), ...
    count_unique_chains(stage_probability_table), ...
    max(stage_probability_table.stage_id), ...
    min(stage_probability_table.stage_cumulative_probability), ...
    max(stage_probability_table.stage_cumulative_probability), ...
    sum(stage_probability_table.stage_cumulative_probability == 0), ...
    sum(isnan(stage_probability_table.stage_cumulative_probability)), ...
    max(stage_probability_table.stage_load_shed_frac), ...
    'VariableNames', {'total_rows', 'unique_chain_count', 'max_stage_id', ...
    'min_stage_cumulative_probability', 'max_stage_cumulative_probability', ...
    'num_zero_stage_probability', 'num_nan_stage_probability', 'max_stage_load_shed_frac'});
end

function n = count_unique_chains(tbl)
%COUNT_UNIQUE_CHAINS 统计事故链数量。
keys = string(tbl.initial_branch) + "_" + string(tbl.trial_id);
n = numel(unique(keys));
end

function n = count_unique_stages(tbl)
%COUNT_UNIQUE_STAGES 统计唯一逐级状态数量。
keys = string(tbl.initial_branch) + "_" + string(tbl.trial_id) + "_" + string(tbl.stage_id);
n = numel(unique(keys));
end

function value = percentile_value(values, pct)
%PERCENTILE_VALUE 不依赖额外工具箱的经验百分位数。
values = sort(values(~isnan(values)));
if isempty(values)
    value = NaN;
    return;
end
idx = max(1, min(numel(values), ceil(pct / 100 * numel(values))));
value = values(idx);
end
